### ISSUE TITLE
Week and day view don't show events while month and list view do

### ISSUE THREAD

**Issue by caasion** [davish/obsidian-full-calendar#122]
**Describe the bug**
Title says all: week and day view don't show events while month and list view do.

**To Reproduce**
1. Creating an event from week view and making it recurring

**Expected behavior**
The event to show on all views

**Screenshots**
![image](https://user-images.githubusercontent.com/103465188/171279774-ddc7b22d-c07f-4d1f-8aa1-7b1d47634ea4.png)
![image](https://user-images.githubusercontent.com/103465188/171279803-e1e3cc64-ad6a-4d56-9b2b-f39dbe00fd9e.png)
![image](https://user-images.githubusercontent.com/103465188/171279823-e49969fe-1822-454b-a138-c942e311b4be.png)
![image](https://user-images.githubusercontent.com/103465188/171279832-b88fd898-5939-4015-9b8a-b4ab638b5c35.png)

**Console Errors**
Go to `View->Toggle Developer Tools` and open up the JavaScript console, reproduce your bug, and copy/paste any logs you see there.

**Device info (please complete the following information):**
 - OS: Ubuntu
 - Plugin Version 0.6.1

**Comment by Lights-dummies** [comment]
Hello!
I've the same problem, also in week and day view is not possible to create events by click in the calendar.

Error:
Obsidian Developer Console
​ Loading Banners...
VM151:20681 Dataview: version 0.5.43 (requires obsidian 0.13.11)
​ loading obsidian-icon-folder
​ FullCalendar VDOM already loaded
app.js:1 Total plugin setup: 2.879ms
obsidian-full-calendar: 1.155ms
obsidian-style-settings: 505ms
obsidian-banners: 439ms
obsidian-itinerary: 423ms
dataview: 229ms
obsidian-icon-folder: 129ms
VM151:13951 Dataview: all 6 files have been indexed in 0.333s (6 cached, 0 skipped).
26
VM153:49400 Uncaught TypeError: Cannot read properties of null (reading 'positions')
    at TimeCols2.queryHit (eval at <anonymous> (app.js:1:1), <anonymous>:49400:32)
    at HitDragging2.queryHitForOffset (eval at <anonymous> (app.js:1:1), <anonymous>:50759:31)
    at HitDragging2.processFirstCoord (eval at <anonymous> (app.js:1:1), <anonymous>:50711:45)
    at HitDragging2.handlePointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50665:13)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at FeaturefulElementDragging2._this.onPointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50490:23)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at HTMLDivElement.PointerDragging2.handleMouseDown (eval at <anonymous> (app.js:1:1), <anonymous>:49908:23)
​ Unloading Banners...
​ unloading obsidian-icon-folder
VM162:38746 FullCalendar VDOM already loaded
14
VM162:49400 Uncaught TypeError: Cannot read properties of null (reading 'positions')
    at TimeCols2.queryHit (eval at <anonymous> (app.js:1:1), <anonymous>:49400:32)
    at HitDragging2.queryHitForOffset (eval at <anonymous> (app.js:1:1), <anonymous>:50759:31)
    at HitDragging2.processFirstCoord (eval at <anonymous> (app.js:1:1), <anonymous>:50711:45)
    at HitDragging2.handlePointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50665:13)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at FeaturefulElementDragging2._this.onPointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50490:23)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at HTMLDivElement.PointerDragging2.handleMouseDown (eval at <anonymous> (app.js:1:1), <anonymous>:49908:23)
VM163:28 Loading Banners...
main.ts:112 Dataview: version 0.5.43 (requires obsidian 0.13.11)
index.ts:153 Dataview: all 6 files have been indexed in 0.225s (6 cached, 0 skipped).
main.ts:35 loading obsidian-icon-folder
vdom.js:7 FullCalendar VDOM already loaded
8
VM162:49400 Uncaught TypeError: Cannot read properties of null (reading 'positions')
    at TimeCols2.queryHit (eval at <anonymous> (app.js:1:1), <anonymous>:49400:32)
    at HitDragging2.queryHitForOffset (eval at <anonymous> (app.js:1:1), <anonymous>:50759:31)
    at HitDragging2.processFirstCoord (eval at <anonymous> (app.js:1:1), <anonymous>:50711:45)
    at HitDragging2.handlePointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50665:13)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at FeaturefulElementDragging2._this.onPointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50490:23)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at HTMLDivElement.PointerDragging2.handleMouseDown (eval at <anonymous> (app.js:1:1), <anonymous>:49908:23)
VM168:38746 FullCalendar VDOM already loaded
VM168:9093 The specified value "hsl(256.26,100%,69.61%)" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.
6
VM168:49400 Uncaught TypeError: Cannot read properties of null (reading 'positions')
    at TimeCols2.queryHit (eval at <anonymous> (app.js:1:1), <anonymous>:49400:32)
    at HitDragging2.queryHitForOffset (eval at <anonymous> (app.js:1:1), <anonymous>:50759:31)
    at HitDragging2.processFirstCoord (eval at <anonymous> (app.js:1:1), <anonymous>:50711:45)
    at HitDragging2.handlePointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50665:13)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at FeaturefulElementDragging2._this.onPointerDown (eval at <anonymous> (app.js:1:1), <anonymous>:50490:23)
    at Emitter2.trigger (eval at <anonymous> (app.js:1:1), <anonymous>:43025:15)
    at HTMLDivElement.PointerDragging2.handleMouseDown (eval at <anonymous> (app.js:1:1), <anonymous>:49908:23)
﻿

OS: Windows 11
Plugin Version 0.6.1.

Many thanks

**Comment by davish** [comment]
It looks like all your events start at 11pm, but the day and week views are scrolled so that 11pm is still out of frame. If you scroll down in those views, you should be able to see your events. There is nothing different between month and week view, if the events are visible in month view, they will also be in week view, unless there's a bug with the underlying FullCalendar rendering.
