### ISSUE TITLE
DataviewJS query may need updating

### ISSUE THREAD

**Issue by matthewturk** [davish/obsidian-full-calendar#47]
**Describe the bug**
Copying the inline DataviewJS query into a note produces an error that `eventClick` can't be destructured from the `undefined` object.  I believe this is because the `renderCalendar` API changed somewhere around a3bfa1da36036df5ea8aa0b8346fef72c226c3e6 .

**To Reproduce**
1. Go to a new note
2. Add this:

````
```dataviewjs
const { renderCalendar } = app.plugins.plugins["obsidian-full-calendar"];
let calendar = renderCalendar(this.container, [{startDate: "2022-01-26", startTime: "17:00", endTime: "22:00", id: "id", title: "This is an event"}]);
calendar.render();
```
````

3. View rendering.

**Expected behavior**
The hardcoded event to be rendered.

**Console Errors**
```
Evaluation Error: TypeError: Cannot destructure property 'eventClick' of 'undefined' as it is undefined.
    at renderCalendar (eval at <anonymous> (app://obsidian.md/app.js:1:1278841), <anonymous>:44875:54)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1278841)), <anonymous>:2:16)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1278841), <anonymous>:15671:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1278841), <anonymous>:15672:7)
    at asyncEvalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1278841), <anonymous>:15682:32)
    at DataviewJSRenderer.render (eval at <anonymous> (app://obsidian.md/app.js:1:1278841), <anonymous>:16267:19)
    at DataviewRefreshableRenderer.maybeRefresh (eval at <anonymous> (app://obsidian.md/app.js:1:1278841), <anonymous>:15995:26)
    at t.e.tryTrigger (app://obsidian.md/app.js:1:762637)
    at t.e.trigger (app://obsidian.md/app.js:1:762570)
    at t.trigger (app://obsidian.md/app.js:1:1257953)
```

**Additional context**

I was able to fix it somewhat by providing an empty function handler for `eventClick`, but I think it may need some modification to fit with the current paradigm.

```
const { renderCalendar, settings } = app.plugins.plugins["obsidian-full-calendar"];
let calendar = renderCalendar(this.container, settings.calendarSources, 
                                { eventClick: () => {} });
calendar.render();
```

For instance, this doesn't do the filtering for `.ics` etc, and also results in CORS errors for remote google calendar secret URLs.

**Comment by davish** [comment]
Yeah, I wrote this section of the documentation a while ago and I'm sorry for it being out of date. I'm planning on moving the documentation to GitHub pages as part of #35, and will update the example when I do that. I'll also make sure that `eventClick` can be undefined and things will still work. Thanks for the report!

**Comment by matthewturk** [comment]
@davish Thank you!
