### ISSUE TITLE
iCloud credential give Error 401 even if correct

### ISSUE THREAD

**Issue by salvlox** [davish/obsidian-full-calendar#547]
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/davish/obsidian-full-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and didn't find any similar reports.

### Expected Behavior

401 Error even with certain correct credential in trying to connect the plugin to the iCloud service

### Current behaviour

The pop up works but the credential are never right, even when their authenticity has been throughly checked

### JavaScript console output

<html>
<body>
<div tabindex="-1" class="console-message-wrapper console-from-api console-error-level" role="log" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: #a00; --console-color-green: #0a0; --console-color-yellow: #a50; --console-color-blue: #00a; --console-color-magenta: #a0a; --console-color-cyan: #0aa; --console-color-gray: #aaa; --console-color-darkgray: #555; --console-color-lightred: #f55; --console-color-lightgreen: #5f5; --console-color-lightyellow: #ff5; --console-color-lightblue: #55f; --console-color-ightmagenta: #f5f; --console-color-lightcyan: #5ff; --console-color-white: #fff; background-color: var(--sys-color-surface-error); --message-corner-rounder-background: var(--sys-color-surface-error); color: rgb(31, 31, 31); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label="plugin:obsidian-full-calendar:63173 Error importing calendars from https://caldav.icloud.com Error: Request failed, status 401
    at new t (app.js:1:1782334)
    at Bq (app.js:1:1782526)
    at app.js:1:1783203
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at a (app.js:1:236367) Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/plugin:obsidian-full-calendar:63173" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">plugin:obsidian-full-calendar:63173</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Error importing calendars from <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">https://caldav.icloud.com</span> <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Request failed, status 401
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at new t (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:1782334" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">app.js:1:1782334</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Bq (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:1782526" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">app.js:1:1782526</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:1783203" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">app.js:1:1783203</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:237544" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">app.js:1:237544</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Object.next (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:237649" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">app.js:1:237649</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at a (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:236367" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--sys-color-primary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">app.js:1:236367</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas,lucida console,courier new,monospace; --source-code-font-size: 12px; --source-code-font-family: consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | eval | @ | plugin:obsidian-full-calendar:63173
-- | -- | -- | --
  | rejected | @ | plugin:obsidian-full-calendar:72
  | Promise.then (async) |   |  
  | step | @ | plugin:obsidian-full-calendar:77
  | eval | @ | plugin:obsidian-full-calendar:78
  | __async | @ | plugin:obsidian-full-calendar:62
  | importCalendars | @ | plugin:obsidian-full-calendar:63134
  | eval | @ | plugin:obsidian-full-calendar:63248
  | eval | @ | plugin:obsidian-full-calendar:78
  | __async | @ | plugin:obsidian-full-calendar:62
  | submit | @ | plugin:obsidian-full-calendar:63245
  | eval | @ | plugin:obsidian-full-calendar:63005
  | eval | @ | plugin:obsidian-full-calendar:78
  | __async | @ | plugin:obsidian-full-calendar:62
  | handleSubmit | @ | plugin:obsidian-full-calendar:63000
  | callCallback2 | @ | plugin:obsidian-full-calendar:11447
  | invokeGuardedCallbackDev | @ | plugin:obsidian-full-calendar:11472
  | invokeGuardedCallback | @ | plugin:obsidian-full-calendar:11506
  | invokeGuardedCallbackAndCatchFirstError | @ | plugin:obsidian-full-calendar:11509
  | executeDispatch | @ | plugin:obsidian-full-calendar:14132
  | processDispatchQueueItemsInOrder | @ | plugin:obsidian-full-calendar:14152
  | processDispatchQueue | @ | plugin:obsidian-full-calendar:14161
  | dispatchEventsForPlugins | @ | plugin:obsidian-full-calendar:14169
  | eval | @ | plugin:obsidian-full-calendar:14293
  | batchedEventUpdates$1 | @ | plugin:obsidian-full-calendar:23817
  | batchedEventUpdates | @ | plugin:obsidian-full-calendar:11327
  | dispatchEventForPluginEventSystem | @ | plugin:obsidian-full-calendar:14292
  | attemptToDispatchEvent | @ | plugin:obsidian-full-calendar:12841
  | dispatchEvent | @ | plugin:obsidian-full-calendar:12796
  | unstable_runWithPriority | @ | plugin:obsidian-full-calendar:8122
  | runWithPriority$1 | @ | plugin:obsidian-full-calendar:16244
  | discreteUpdates$1 | @ | plugin:obsidian-full-calendar:23831
  | discreteUpdates | @ | plugin:obsidian-full-calendar:11337
  | dispatchDiscreteEvent | @ | plugin:obsidian-full-calendar:12777

</span></div></div></div></div></div>
</body>
</html>

### Steps to reproduce

1. try and connect the full calendar to icloud
2. insert proper credential
3. receive 401 error through pop up in right up corner

### Calendar information

standard iCloud service calendar

### Which Operating Systems are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] iOS

### Obsidian Version

1.5.8

### Full Calendar Plugin Version

0.10.7

### Checks

- [ ] I have tried it with all other plugins disabled and the error still occurs.

**Comment by yaoyhu** [comment]
You can't just sign in your iCloud account within your Apple password (it's not like api-key, Apple has to make sure that your Apple ID password can't be stored or collected by other platform). 

The soulution is to **create an app-specific password**, you can find instructions here: https://support.apple.com/en-us/102654.

After creating the passwords, use your AppleID and the given `app-specific password` provided by apple to login again.

<img width="715" alt="image" src="https://github.com/davish/obsidian-full-calendar/assets/86143910/538d61fe-5d42-4db3-a6c3-8729c32eb004">

**Comment by giittyy** [comment]
That doesn't work. 

> You can't just sign in your iCloud account within your Apple password (it's not like api-key, Apple has to make sure that your Apple ID password can't be stored or collected by other platform).
> 
> The soulution is to **create an app-specific password**, you can find instructions here: https://support.apple.com/en-us/102654.
> 
> After creating the passwords, use your AppleID and the given `app-specific password` provided by apple to login again.
> 
> <img alt="image" width="715" src="https://private-user-images.githubusercontent.com/86143910/326144422-538d61fe-5d42-4db3-a6c3-8729c32eb004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMTc4OTksIm5iZiI6MTcyNDAxNzU5OSwicGF0aCI6Ii84NjE0MzkxMC8zMjYxNDQ0MjItNTM4ZDYxZmUtNWQ0Mi00ZGIzLWE2YzMtODcyOWMzMmViMDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDIxNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmViYjY1MmRiM2FkYjA1NTk0MjZiNTA3MjVjM2VmMTAyZDFmZmJjNDI2ZjRjYTFkZTk3Y2MzNjg5MjFjZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BF5dVCQ5B_qmubMhY6DN5kaxac_Nj_oTtdyGyy5CPps">

That doesn't work. Same 401 error

**Comment by Youmatt** [comment]
Its work. Thank you

**Comment by Maxwilson1101** [comment]
It works. Thx!

**Comment by justinxueba** [comment]
I encountered the same issue, even after correctly entering the Apple ID and `app-specific password`, Error 401 still occurs
