### ISSUE TITLE
Bug : Dataview example from wiki throws 'Cannot destructure property' error (workaround provided)

### ISSUE THREAD

**Issue by JeremieSpiesser** [davish/obsidian-full-calendar#69]
The following dataview example taken from [the wiki ](https://davish.github.io/obsidian-full-calendar/advanced/dataview/) 

````
this.container.style.minHeight = "500px";
const { renderCalendar } = app.plugins.plugins["obsidian-full-calendar"];
let calendar = renderCalendar(this.container, [[]]);
calendar.render()
````

throws this error : 

```
Evaluation Error: TypeError: Cannot destructure property 'eventClick' of 'undefined' as it is undefined.
    at renderCalendar (eval at <anonymous> (app://obsidian.md/app.js:1:1), <anonymous>:44875:54)
    at eval (eval at <anonymous> (eval at <anonymous> (app://obsidian.md/app.js:1:1)), <anonymous>:3:16)
    at DataviewInlineApi.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1), <anonymous>:15671:16)
    at evalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1), <anonymous>:15672:7)
    at asyncEvalInContext (eval at <anonymous> (app://obsidian.md/app.js:1:1), <anonymous>:15682:32)
    at DataviewJSRenderer.render (eval at <anonymous> (app://obsidian.md/app.js:1:1), <anonymous>:16267:19)
    at DataviewRefreshableRenderer.maybeRefresh (eval at <anonymous> (app://obsidian.md/app.js:1:1), <anonymous>:15995:26)
    at t.e.tryTrigger (app://obsidian.md/app.js:1:838297)
    at t.e.trigger (app://obsidian.md/app.js:1:838230)
    at t.trigger (app://obsidian.md/app.js:1:1406877)
```

the solution is to add an empty settings object to the renderCalendar function, so the dataview code is instead : 

```
this.container.style.minHeight = "800px";
const { renderCalendar } = app.plugins.plugins["obsidian-full-calendar"];
let calendar = renderCalendar(this.container, [[]] , {});
calendar.render()
```

Maybe this has to do with something in line 28 of the file calendar.ts

**Comment by davish** [comment]
Hi @JeremieSpiesser, this has been fixed on the main branch, but I haven't yet cut a release with the bugfix. I'll leave this issue open until I cuz the next release. 

Sorry for the confusion!
