### ISSUE TITLE
Full Calendar not show up 

### ISSUE THREAD

**Issue by BrotherGarfield** [davish/obsidian-full-calendar#84]
**Describe the bug**
Full Calendar not show up after I installed other plugins

**To Reproduce**
<img width="199" alt="Screen Shot 2022-04-06 at 18 11 43" src="https://user-images.githubusercontent.com/103104857/162101889-8729016f-e468-4d3d-b63c-501385d1a95d.png">
List of plugin installed

**Expected behavior**
I guess its confilct with other plugin/plugins, but have no clue.

**Screenshots**
<img width="830" alt="Screen Shot 2022-04-06 at 18 13 48" src="https://user-images.githubusercontent.com/103104857/162102093-9c89d78d-4e5d-4e92-bd6a-b9a9abc56fb7.png">

**Console Errors**
app.js:1 Failed to open view Error: Invalid unit value NaN
    at asNumber (eval at <anonymous> (app.js:1:1444405), <anonymous>:26574:15)
    at normalizeObject (eval at <anonymous> (app.js:1:1444405), <anonymous>:26584:40)
    at DateTime4.set (eval at <anonymous> (app.js:1:1444405), <anonymous>:30303:26)
    at add (eval at <anonymous> (app.js:1:1444405), <anonymous>:45143:15)
    at parseFrontmatter (eval at <anonymous> (app.js:1:1444405), <anonymous>:45189:36)
    at _NoteEvent.toCalendarEvent (eval at <anonymous> (app.js:1:1444405), <anonymous>:45312:12)
    at NoteSource.eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:45785:31)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1444405), <anonymous>:66:61)
    at new Promise (<anonymous>)

**Device info (please complete the following information):**
 - OS: [MacOS 12.3]
 - Plugin Version [0.5.3]

**Additional context**

**Comment by davish** [comment]
Hello @BrotherGarfield,

I unfortunately can't debug issues that are caused by other plugins. Please try deactivating some of your other plugins to see if it helps in bringing Full Calendar back.

**Comment by davish** [comment]
You can try the Divide and Conquer plugin to help you out: https://github.com/chrisgrieser/obsidian-divide-and-conquer

**Comment by BrotherGarfield** [comment]
This issue is caused by a mis-typing in YAML

title: meeting title
allDay: false
startTime: 18:00
endTime: 18-30
date: 2022-04-24

"endTime" should be "18:30", not "18-30"

After I correct the endTime, Full Calendar works.

I guess the bug is in processing the "YAML" data, not cause by other plugins

杨巍 (Yang, Wei)


Davis Haupt ***@***.***> 于2022年4月22日周五 07:53写道：
